<a href="https://colab.research.google.com/github/Muluken1Walle/Numpy_KAG_Conversion_Data_Project/blob/main/PathkAGConversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
project_data = 'KAG_Conversion_Data.csv'

In [ ]:
import numpy as np
KageDataStr= np.genfromtxt(project_data, delimiter=',', skip_header=1,dtype=str)
KageDataFloat = np.genfromtxt(project_data,delimiter=',',skip_header=1,dtype=float)

In [ ]:
KageDataStr

array([['708746', '916', '103916', ..., '1.429999948', '2', '1'],
       ['708749', '916', '103917', ..., '1.820000023', '2', '0'],
       ['708771', '916', '103920', ..., '0', '1', '0'],
       ...,
       ['1314412', '1178', '179979', ..., '40.28999949', '2', '0'],
       ['1314414', '1178', '179981', ..., '198.7100005', '8', '2'],
       ['1314415', '1178', '179982', ..., '165.6099987', '5', '2']],
      dtype='<U11')

In [ ]:
KageDataFloat

array([[7.08746000e+05, 9.16000000e+02, 1.03916000e+05, ...,
        1.42999995e+00, 2.00000000e+00, 1.00000000e+00],
       [7.08749000e+05, 9.16000000e+02, 1.03917000e+05, ...,
        1.82000002e+00, 2.00000000e+00, 0.00000000e+00],
       [7.08771000e+05, 9.16000000e+02, 1.03920000e+05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [1.31441200e+06, 1.17800000e+03, 1.79979000e+05, ...,
        4.02899995e+01, 2.00000000e+00, 0.00000000e+00],
       [1.31441400e+06, 1.17800000e+03, 1.79981000e+05, ...,
        1.98710001e+02, 8.00000000e+00, 2.00000000e+00],
       [1.31441500e+06, 1.17800000e+03, 1.79982000e+05, ...,
        1.65609999e+02, 5.00000000e+00, 2.00000000e+00]])

In [ ]:
type(KageDataStr)

numpy.ndarray

In [ ]:
type(KageDataFloat)

numpy.ndarray

In [ ]:
H = KageDataStr[:,1]
np.unique(H,return_counts=True)

(array(['1178', '916', '936'], dtype='<U11'), array([625,  54, 464]))

In [ ]:
unique_id ,count = np.unique(H,return_counts=True)
print(unique_id)
print(count)

['1178' '916' '936']
[625  54 464]


In [ ]:
for i in range(len(unique_id)):
  print('{} ran {} times'.format(unique_id[i],count[i]))

1178 ran 625 times
916 ran 54 times
936 ran 464 times


In [ ]:
age = KageDataStr[:,3]
UniquAgeGroup= np.unique(age)
print(UniquAgeGroup)

['30-34' '35-39' '40-44' '45-49']


In [ ]:
Spent =KageDataFloat[:,8]
print(Spent)
AvgSpent= Spent.mean()
MinSpent= Spent.min()
MaxSpent = Spent.max()
print('The average amount spent on ads',AvgSpent)
print('the minimum amount spent on ads', MinSpent)
print('The Maximum amount spent on ads', MaxSpent)

[  1.42999995   1.82000002   0.         ...  40.28999949 198.7100005
 165.6099987 ]
The average amount spent on ads 51.36065613141295
the minimum amount spent on ads 0.0
The Maximum amount spent on ads 639.9499981


In [ ]:
Id = KageDataFloat[:,0]
print(Id)
Click= KageDataFloat[:,7]
print(Click)

[ 708746.  708749.  708771. ... 1314412. 1314414. 1314415.]
[  1.   2.   0. ...  28. 135. 114.]


In [ ]:
maxc= Click.max()
print('The maximum number of clicks is',maxc)


The maximum number of clicks is 421.0


In [ ]:
max_click_id = Id[Click==maxc]
print('Id of the ad having the maximum number of clicks', max_click_id)

Id of the ad having the maximum number of clicks [1121814.]


In [ ]:
Aconversion = KageDataFloat[:,10]
print(Aconversion)
ac= Aconversion[Click== maxc]
print('the aproved conversion after seen the ads the most click',ac)

[1. 0. 0. ... 0. 2. 2.]
the aproved conversion after seen the ads the most click [13.]


In [ ]:
maxs= Aconversion.max()
print('the maximum numbe of purchase is',maxs)


the maximum numbe of purchase is 21.0


In [ ]:
KageDataFloat[Aconversion==21.0]

array([[1.12110400e+06, 1.17800000e+03, 1.44533000e+05,            nan,
                   nan, 1.60000000e+01, 2.08066600e+06, 2.02000000e+02,
        3.60150001e+02, 4.00000000e+01, 2.10000000e+01]])